services:
  test:
    build: .
    # ports:
    # - "8082:3000"
    restart: always

    working_dir: /app
    volumes:
      - $PWD/app:/app

    command: sleep infinity
    # labels:
    #   - 'traefik.enable=true'
    #   - 'traefik.http.routers.whoami.rule=Host(`portfolio.iamon99.com`)'
    #   - 'traefik.http.routers.whoami.entrypoints=websecure'
    #   - 'traefik.http.routers.whoami.tls.certresolver=myresolver'
